# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2019 CERN.
# Copyright (C) 2018-2019 RERO.
#
# Invenio-Circulation is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

dist: trusty

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel EXTRAS=all,elasticsearch7 ES_URL=$ES7_DOWNLOAD_URL

cache:
  - pip

services:
  - redis

env:
  global:
    - ES5_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.16.tar.gz"
    - ES6_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.2.tar.gz"
    - ES7_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.0-linux-x86_64.tar.gz"
    - ES_HOST=127.0.0.1
  matrix:
    - REQUIREMENTS=lowest EXTRAS=all,sqlite,elasticsearch5 ES_URL=$ES5_DOWNLOAD_URL
    - REQUIREMENTS=lowest EXTRAS=all,sqlite,elasticsearch6 ES_URL=$ES6_DOWNLOAD_URL
    - REQUIREMENTS=release EXTRAS=all,sqlite,elasticsearch6 ES_URL=$ES6_DOWNLOAD_URL
    - REQUIREMENTS=release EXTRAS=all,sqlite,elasticsearch7 ES_URL=$ES7_DOWNLOAD_URL DEPLOY=true
    - REQUIREMENTS=devel EXTRAS=all,sqlite,elasticsearch7 ES_URL=$ES7_DOWNLOAD_URL

python:
  - "3.5"

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch > /tmp/local-es.log &"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[$EXTRAS]"
  - "pip freeze"

before_script:
  # Allow ES to start
  - sleep 5
  - curl http://127.0.0.1:9200 && echo "Elasticsearch is up!" || cat /tmp/local-es.log

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  distributions: sdist bdist_wheel
  on:
    condition: $DEPLOY = true
    python: '3.5'
    repo: inveniosoftware/invenio-circulation
    tags: true
  password:
    secure: 0AV0IlCIHu6/4OL9LQvLvR9T8CWm1luBRbOhpiNhQfM7O5SWmpMHFUoCee5D23XxYabCzen/qS0yQeuz6MyW5eO6WM56KigWjI43Hx0/284GI+irnR9+P8aJYA1MIwg7ug9aRts73yd5/u+HJ5IAxEyzTf6ilzFRErgU0VQVcdaOgTRrqQlYA+d9xnHthw9UXtdJUFjqapGmibfPV/YoP2O6ReVahNcgzWSO4wosiAlqy5IHqM/x7EJ81BNHrNVF4ZXKe2y24k1uV8LmCZN7aEQKaLWZNxLpZNaEv+QKAhvmhSlJMh086kzr+Fs7xDXiAZW9x3xVGL908ZlQyzBkJbNE1UUL4KOa2IcSu/Sfpl9zZCQpH8mD/wnjsSIWQ0j3fZPyLBaSSKLUvH3Pr7NLbr1xnQjEILPW3vgNOGbKl/8X4X46Ziact6rf4tIr6IctqzdfYem0FEYhhpBIFTrYtzTGBf5AQfnr2+x3D2ixk89Wy42UzYqwiZMXUMC3eVayrbYEpn7aYeGbinz84D2xSSYVuagtghKxl8wy1+anUbuWEhkS9rJMLK9BLQAuh41+M3kRcS1788CZw0wB7UzgcWUWy7yYP4X2bbVnzUnBPsxhHhkFIGXRSfTdABVGvCVmBDEvwAVbdPb5YrreowS4phfHhseTvOXv56rn4UAaFLI=
  provider: pypi
  user: inveniosoftware
